# Generated by Django 3.0.4 on 2020-03-21 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=100)),
                ('unit_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Unit')),
                ('unit_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_b', to='monitoring.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Indicator')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Scale'),
        ),
    ]
