# Generated by Django 3.0.4 on 2020-03-21 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=100)),
                ('unit_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Unit')),
                ('unit_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_b', to='monitoring.Unit')),
            ],
        ),
    ]
