# Generated by Django 3.0.4 on 2020-03-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_indicatorcomposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='formula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
