# Generated by Django 3.0.4 on 2020-03-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='acronym',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
