# Generated by Django 3.0.4 on 2020-03-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_unit_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorcontext',
            name='chart',
            field=models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('horizontalBar', 'Horizontal Bar')], default='line', max_length=20),
        ),
    ]
