# Generated by Django 3.0.4 on 2020-03-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20200323_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorcontext',
            name='interval',
            field=models.CharField(choices=[('millisecond', 'Milliseconds'), ('second', 'Seconds'), ('minute', 'Minutes'), ('hour', 'Hours'), ('day', 'Days'), ('week', 'Weeks'), ('month', 'Months'), ('quarter', 'Quarters'), ('year', 'Years')], default='day', max_length=20),
        ),
    ]
